### ISSUE TITLE
Unable to get tincanapi prototype working with OpenLRS

### ISSUE THREAD

**Issue by redraushan** [Apereo-Learning-Analytics-Initiative/OpenLRS#26]
I was trying to integrate tincanapi prototype with OpenLRS. 
Source : http://tincanapi.com/prototypes-getting-started/
I am running OpenLRS in my localhost with in memory database by following the getting started guide (http://apereo-learning-analytics-initiative.github.io/OpenLRS/)

Fortunately, some of the statements are being recorded but there are few calls that goes 404.While playing golf-course

**Request URL :**
 http://localhost:8092/v1/xAPI/activities/state?stateId=bookmarking-data&activityId=http%3A%2F%2Fid.tincanapi.com%2Factivity%2Ftincan-prototypes%2Fgolf-example&agent=%7B%22objectType%22%3A%22Agent%22%2C%22mbox%22%3A%22mailto%3Araushan.sharma%40sparkwork.io%22%2C%22name%22%3A%22Raushan%20Sharma%22%7D&registration=12315a27-9c9e-4bfe-a37b-a2ae4e555e31

Request **Method:POST**

**Response :** 

{"timestamp":"2016-08-31T19:36:28.376+0000","status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/v1/xAPI/activities/state"}

**Similarly while playing tetris prototype, I get following error :** 

**Request URL:**
http://localhost:8092/v1/xAPI/activities/profile?profileId=highscores&activityId=http%3A%2F%2Fid.tincanapi.com%2Factivity%2Ftincan-prototypes%2Ftetris

**Request Method:GET**

**Response**
{"timestamp":"2016-08-31T19:58:33.844+0000","status":404,"error":"Not Found","message":"No message available","path":"/v1/xAPI/activities/profile"}

If you need any further information to make it clear, please let me know.
Thanks you guys for your hard work and sorry for being complete noob.

**Comment by gryglbrt** [comment]
Hi, 

The short answer is that OpenLRS does not yet support the xAPI state or profile APIs. The state API is certainly something we feel is very important, and I know others in the community have looked at it, but it has not made it on to our roadmap yet.

Thank you for your interest and please consider contributing to the project.

Best,
Gary

**Comment by redraushan** [comment]
Thanks Gary! It's always great to hear from you. I will sure make my contributions. I am thinking about how I can do so.

Regards!
