### ISSUE TITLE
Mistake in XApiToCaliperConversionService, while converting an Event to xAPI

### ISSUE THREAD

**Issue by venkatapathy** [Apereo-Learning-Analytics-Initiative/OpenLRS#35]
Hi,

First of all, thanks for this great OpenSource LRS, that too in Java, with so many features enabled- I am loving it. Ok, I think I found a bug(?) or I am not sure if it was intended. During retrieval of xAPI statements, XApiToCaliperConversionService converts a general event to xAPI right? During the conversion of Action from Event to xAPI, it checks if the Action is present in Caliper and if not it defaults to Caliper  Action: initialized. Result: All the action of the xAPI statements default to 'Initialize'. I believe it is not the intention and is a bug? Since I am not familiar with Caliper and if this behavior is intended by you guys. In any case, I forked and changed the line:
```
- xapiVerb.setId(caliperActionToXapiVerb(action));
+ xapiVerb.setId(action);
```

Let me know, if this is correct, and I can request you a pull request for the change :)

Venkat

**Comment by gryglbrt** [comment]
Thanks Venkat,

If I may call your attention to our new project - https://github.com/Apereo-Learning-Analytics-Initiative/OpenLRW. Over time this project will replace OpenLRS. Please take a look and if it meets your needs I would suggest that you start using OpenLRW instead of OpenLRS.

Best,
Gary

**Comment by venkatapathy** [comment]
Ok, Thank you for the suggestion. Will take a look at it :)

Regards,
Venkat
